// <auto-generated />
using System;
using Infrastructure.Db.App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Db.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Db.App.Entities.AuctionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by")
                        .HasComment("Кто создал сущность.");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency_code")
                        .HasComment("Код валюты.");

                    b.Property<decimal?>("CurrentPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_price")
                        .HasComment("Текущая цена.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by")
                        .HasComment("Кто удалил сущность.");

                    b.Property<long>("DomainId")
                        .HasColumnType("bigint")
                        .HasColumnName("domain_id")
                        .HasComment("Идентификатор домена.");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at")
                        .HasComment("Плановое завершение торгов.");

                    b.Property<DateTimeOffset?>("ExtendedEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extended_end_at")
                        .HasComment("Продленное завершение торгов.");

                    b.Property<string>("ExternalAuctionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_auction_id")
                        .HasComment("Внешний идентификатор лота на площадке.");

                    b.Property<decimal?>("FinalPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("final_price")
                        .HasComment("Финальная цена.");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at")
                        .HasComment("Время финализации.");

                    b.Property<bool?>("IsExtended")
                        .HasColumnType("boolean")
                        .HasColumnName("is_extended")
                        .HasComment("Торги продлены.");

                    b.Property<DateTimeOffset?>("LastObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at")
                        .HasComment("Последнее обработанное время наблюдения.");

                    b.Property<string>("LotUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("lot_url")
                        .HasComment("Ссылка на лот.");

                    b.Property<long>("SourcePlatformId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_platform_id")
                        .HasComment("Идентификатор площадки.");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at")
                        .HasComment("Старт торгов.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status")
                        .HasComment("Текущий нормализованный статус торгов.");

                    b.Property<string>("TerminalStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("terminal_status")
                        .HasComment("Финальный terminal статус.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by")
                        .HasComment("Кто обновил сущность.");

                    b.HasKey("Id")
                        .HasName("pk_auctions");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("ix_auctions_domain_id");

                    b.HasIndex("EndAt");

                    b.HasIndex("LastObservedAt");

                    b.HasIndex("Status");

                    b.HasIndex("SourcePlatformId", "ExternalAuctionId")
                        .IsUnique();

                    b.ToTable("auctions", "app", t =>
                        {
                            t.HasComment("Торги домена на конкретной площадке.");
                        });
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.AuctionObservationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AttributesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes_json")
                        .HasComment("Расширяемые атрибуты (json/string).");

                    b.Property<long>("AuctionId")
                        .HasColumnType("bigint")
                        .HasColumnName("auction_id")
                        .HasComment("Связанные торги.");

                    b.Property<string>("AuctionStatusNormalized")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("auction_status_normalized")
                        .HasComment("Нормализованный статус.");

                    b.Property<string>("AuctionStatusRaw")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("auction_status_raw")
                        .HasComment("Сырой статус источника.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by")
                        .HasComment("Кто создал сущность.");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency_code")
                        .HasComment("Код валюты.");

                    b.Property<decimal?>("CurrentPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_price")
                        .HasComment("Наблюдаемая цена.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by")
                        .HasComment("Кто удалил сущность.");

                    b.Property<decimal?>("FinalPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("final_price")
                        .HasComment("Наблюдаемая финальная цена.");

                    b.Property<bool>("IsOutOfOrder")
                        .HasColumnType("boolean")
                        .HasColumnName("is_out_of_order")
                        .HasComment("Признак out-of-order события.");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("message_id")
                        .HasComment("Уникальный идентификатор сообщения.");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at")
                        .HasComment("Время фактического наблюдения.");

                    b.Property<string>("ParserCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("parser_code")
                        .HasComment("Код парсера/producer.");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("parser_version")
                        .HasComment("Версия парсера/producer.");

                    b.Property<string>("RawPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload")
                        .HasComment("Сырой payload источника (json/string).");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("schema_version")
                        .HasComment("Версия схемы сообщения.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by")
                        .HasComment("Кто обновил сущность.");

                    b.HasKey("Id")
                        .HasName("pk_auction_observations");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ObservedAt");

                    b.HasIndex("AuctionId", "ObservedAt");

                    b.ToTable("auction_observations", "app", t =>
                        {
                            t.HasComment("История observation-сообщений по торгам.");
                        });
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.AuctionStatusHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuctionId")
                        .HasColumnType("bigint")
                        .HasColumnName("auction_id")
                        .HasComment("Связанные торги.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by")
                        .HasComment("Кто удалил сущность.");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_terminal")
                        .HasComment("Признак terminal статуса.");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("new_status")
                        .HasComment("Новый статус.");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at")
                        .HasComment("Время наблюдения статуса.");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("previous_status")
                        .HasComment("Статус до изменения.");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source")
                        .HasComment("Источник изменения статуса.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by")
                        .HasComment("Кто обновил сущность.");

                    b.HasKey("Id")
                        .HasName("pk_auction_status_history");

                    b.HasIndex("AuctionId", "NewStatus");

                    b.HasIndex("AuctionId", "ObservedAt");

                    b.ToTable("auction_status_history", "app", t =>
                        {
                            t.HasComment("История смены статусов торгов.");
                        });
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.DomainEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by")
                        .HasComment("Кто удалил сущность.");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_normalized")
                        .HasComment("Нормализованное имя домена.");

                    b.Property<string>("NameOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_original")
                        .HasComment("Оригинальное имя домена.");

                    b.Property<string>("NamePunycode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_punycode")
                        .HasComment("Punycode представление домена.");

                    b.Property<string>("Sld")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sld")
                        .HasComment("SLD часть доменного имени.");

                    b.Property<string>("Tld")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tld")
                        .HasComment("Домен верхнего уровня.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by")
                        .HasComment("Кто обновил сущность.");

                    b.HasKey("Id")
                        .HasName("pk_domains");

                    b.HasIndex("NameNormalized")
                        .IsUnique();

                    b.HasIndex("NamePunycode");

                    b.ToTable("domains", "app", t =>
                        {
                            t.HasComment("Домен в нормализованном виде.");
                        });
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.ReceiverProcessingLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by")
                        .HasComment("Кто удалил сущность.");

                    b.Property<string>("ExternalAuctionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_auction_id")
                        .HasComment("Внешний идентификатор торгов.");

                    b.Property<string>("Message")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("message")
                        .HasComment("Описание результата или ошибки.");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("message_id")
                        .HasComment("MessageId сообщения.");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at")
                        .HasComment("Время фактической обработки.");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("result_code")
                        .HasComment("Код результата обработки.");

                    b.Property<string>("SourcePlatformCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_platform_code")
                        .HasComment("Код платформы.");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id")
                        .HasComment("TraceId запроса/обработки.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by")
                        .HasComment("Кто обновил сущность.");

                    b.HasKey("Id")
                        .HasName("pk_receiver_processing_logs");

                    b.HasIndex("MessageId");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("SourcePlatformCode", "ExternalAuctionId");

                    b.ToTable("receiver_processing_logs", "app", t =>
                        {
                            t.HasComment("Лог обработки сообщения receiver-пайплайном.");
                        });
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.SourcePlatformEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code")
                        .HasComment("Код платформы (уникальный).");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by")
                        .HasComment("Кто удалил сущность.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name")
                        .HasComment("Человекочитаемое название платформы.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by")
                        .HasComment("Кто обновил сущность.");

                    b.HasKey("Id")
                        .HasName("pk_source_platforms");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("source_platforms", "app", t =>
                        {
                            t.HasComment("Площадка-источник торгов.");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "nicksell",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "NickSell"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "godaddy",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "GoDaddy"
                        });
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.StatEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by")
                        .HasComment("Кто удалил сущность.");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type")
                        .HasComment("Тип события");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by")
                        .HasComment("Кто обновил сущность.");

                    b.HasKey("Id")
                        .HasName("pk_stat_events");

                    b.ToTable("stat_events", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.AuctionEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.DomainEntity", "Domain")
                        .WithMany("Auctions")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auctions_domains_domain_id");

                    b.HasOne("Infrastructure.Db.App.Entities.SourcePlatformEntity", "SourcePlatform")
                        .WithMany("Auctions")
                        .HasForeignKey("SourcePlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auctions_source_platforms_source_platform_id");

                    b.Navigation("Domain");

                    b.Navigation("SourcePlatform");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.AuctionObservationEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.AuctionEntity", "Auction")
                        .WithMany("Observations")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auction_observations_auctions_auction_id");

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.AuctionStatusHistoryEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.AuctionEntity", "Auction")
                        .WithMany("StatusHistory")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auction_status_history_auctions_auction_id");

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.AuctionEntity", b =>
                {
                    b.Navigation("Observations");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.DomainEntity", b =>
                {
                    b.Navigation("Auctions");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.SourcePlatformEntity", b =>
                {
                    b.Navigation("Auctions");
                });
#pragma warning restore 612, 618
        }
    }
}
