//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramBot.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotStrings_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotStrings_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelegramBot.Resources.Localization.BotStrings.ru", typeof(BotStrings_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написать врачу.
        /// </summary>
        internal static string ButtonDoctorChat {
            get {
                return ResourceManager.GetString("ButtonDoctorChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль врача.
        /// </summary>
        internal static string ButtonDoctorProfile {
            get {
                return ResourceManager.GetString("ButtonDoctorProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть приложение.
        /// </summary>
        internal static string ButtonOpenApp {
            get {
                return ResourceManager.GetString("ButtonOpenApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Служба поддержки.
        /// </summary>
        internal static string ButtonSupport {
            get {
                return ResourceManager.GetString("ButtonSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приветствую вас в ботe врача &lt;b&gt;{0}&lt;/b&gt;.
        /// </summary>
        internal static string MsgDoctorProfile {
            get {
                return ResourceManager.GetString("MsgDoctorProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы начать — выберите нужный пункт из меню ниже 👇.
        /// </summary>
        internal static string MsgMainState {
            get {
                return ResourceManager.GetString("MsgMainState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, я бот одонта.
        /// </summary>
        internal static string MsgStartBot {
            get {
                return ResourceManager.GetString("MsgStartBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to burtimax.
        /// </summary>
        internal static string SupportUsername {
            get {
                return ResourceManager.GetString("SupportUsername", resourceCulture);
            }
        }
    }
}
