//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramBot.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelegramBot.Resources.Localization.BotStrings", typeof(BotStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with doctor.
        /// </summary>
        internal static string ButtonDoctorChat {
            get {
                return ResourceManager.GetString("ButtonDoctorChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor profile.
        /// </summary>
        internal static string ButtonDoctorProfile {
            get {
                return ResourceManager.GetString("ButtonDoctorProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open app.
        /// </summary>
        internal static string ButtonOpenApp {
            get {
                return ResourceManager.GetString("ButtonOpenApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write support.
        /// </summary>
        internal static string ButtonSupport {
            get {
                return ResourceManager.GetString("ButtonSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weclome you in bot doctor {0}.
        /// </summary>
        internal static string MsgDoctorProfile {
            get {
                return ResourceManager.GetString("MsgDoctorProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started, select the desired item from the menu below 👇.
        /// </summary>
        internal static string MsgMainState {
            get {
                return ResourceManager.GetString("MsgMainState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world!!!.
        /// </summary>
        internal static string MsgStartBot {
            get {
                return ResourceManager.GetString("MsgStartBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to burtimax.
        /// </summary>
        internal static string SupportUsername {
            get {
                return ResourceManager.GetString("SupportUsername", resourceCulture);
            }
        }
    }
}
