<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Burtimax.TelegramBot.MultipleBotFramework" Version="2.1.7" />
        <PackageReference Include="Burtimax.TelegramBot.MultipleBotFramework.Endpoints" Version="2.1.7" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2"/>
        <PackageReference Include="Quartz" Version="3.13.1" />
        <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.13.1" />
        <PackageReference Include="Quartz.Extensions.Hosting" Version="3.13.1" />
        <PackageReference Include="Telegram.BotAPI" Version="8.3.0" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\Localization\BotStrings.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>BotStrings.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Localization\BotStrings.ru.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>BotStrings.ru.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\Localization\BotStrings.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>BotStrings.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\Localization\BotStrings.ru.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>BotStrings.ru.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

</Project>
